### PR TITLE
Adding Support for additional ELB log fields

### PR DESCRIPTION
**Pull request by ssayala**

### CODE REVIEW

**Comment by ssayala** [comment]
done.

**Comment by kpkristjansson** [comment]
+1

**Comment by ctrlrsf** [comment]
@ssayala This change allows processing of access logs with the user agent and SSL fields, but doesn't process the older access logs that don't have these fields. When data.length doesn't equal 15 (new access log format) an error is being thrown on line 86 (https://github.com/ssayala/elb2loggly/blob/master/elb2loggly.js#L86).

Could you update PR so both formats are supported?

We're seeing an ELB in production that's logging both access log formats.

To troubleshoot I replaced line 86 with:

```
    console.error("Error parsing line, expecting " + expectedFields + " actual fields " + data.length);
    console.error("Line: " + data);
    done()
```

And here's what I see in CloudWatch logs:

```
2015-08-03T17:44:10.183Z    xxxxxxxxxxx Error parsing line, expecting 15 actual fields 12 
2015-08-03T17:44:10.183Z    xxxxxxxxxxx Line: 2015-08-03T17:35:41.473370Z,xxxxx-production,xxx.xxx.xxx.xxx:21310,10.xxx.xxx.xxx:443,0.000065,0.081609,0.000043,200,200,0,2,GET https://xxxxxxxxx:443/xxxxxx HTTP/1.1
```

**Comment by MarcFletcher** [comment]
Just to update, I am working on integrating this PR alongside mine as I need both.

**Comment by ssayala** [comment]
Ahh..did not realize AWS supporting both access formats. Will try to work on supporting both formats

**Comment by MarcFletcher** [comment]
@ssayala - I've already done this, it's in my most recent PR

**Comment by cboscolo** [comment]
I will merge @Karnifexx's PR into master.  I won't be able to test it myself for a week, so if someone else could bless it I would appreciate that.  Also, if anyone has AWS support and is willing to open a ticket with Amazon to find out how to force the ELBs to log the three new fields I would greatly appreciate that as well.

**Comment by MarcFletcher** [comment]
This can probably be closed as it has been merged via my own PR #6

**Pull request closed without merging**
