### PR TITLE
Added array NUMERIC_COL_INDEX that can be used to define numeric colu…

### PR DESCRIPTION
**Pull request by MarcFletcher**
…mns. Separated url path and url query parameters so that we can split by url path. Added function to obscure query parameters to ensure we don't leak secret information.

### CODE REVIEW

**Comment by cboscolo** [comment]
@Karnifexx thanks for adding the numeric conversion and url param obscuring.

I'd like to preserve a way for users to configure the features of the script without needing to change the code.  I settled on using S3 tags to do this.

Could you make the following changes to your code:
1. Provide for a way to set this via the S3 bucket tag similar to how you can set the loggly token?  (Perhaps an S3 tag called 'elb2loggly-private-url-params' containing a comma-separated list of URL params.)
2. Have it default to the empty set rather than "authToken"?  (Since the ELB logs also have them in plain text, I think that is the right default.) 
3. Update the README on how to configure this new feature and what it does?

Thanks!

**Comment by MarcFletcher** [comment]
Thanks for the feedback, agree in all cases. I will try to do this over the next few days.

**Comment by MarcFletcher** [comment]
I have updated the pull request as requested.

**Comment by MarcFletcher** [comment]
I have updated this PR to include the necessary support for HTTPs, with fallback for cases where there is not HTTPs information. Everything appears to be working correctly, apart from that loggly is not parsing the JSON fields. Here is a COPY/PASTE of a raw message in loggly:

```
{"timestamp":"2015-08-04T16:20:43.243546Z","elb":"lb-frontend-2015","client_ip":"213.163.171.132","client_port":"4921","backend":"10.0.1.131","backend_port":"81","request_processing_time":0.000023,"backend_processing_time":0.021688,"response_processing_time":0.000026,"elb_status_code":"200","backend_status_code":"200","received_bytes":0,"sent_bytes":28,"request_method":"GET","request_url":"https://www.example.com:443/api/lastsharetime","request_query_params":"authToken=177sdfdugd...&accountApiId=&_=1438692134393","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:29.0) Gecko/20100101 Firefox/29.0","ssl_cipher":"ECDHE-RSA-AES128-GCM-SHA256","ssl_protocol":"TLSv1.2"}
```

I will open a support ticket directly with loggly for that as the JSON is valid, not sure why it's not getting parsed.

**Comment by MarcFletcher** [comment]
Apparently I had hit my field limit within loggly ;) Too much playing around. Everything should be working ok.

**Pull request merged**
